### ISSUE TITLE
Help!!!!

### ISSUE THREAD

**Issue by terencekam** [JoseGamerPT/RealScoreboard#12]
i got this error
`:37] [Server thread/WARN]: [RealScoreboard] Task #63 for RealScoreboard v11-4-2020 Build 1 generated an exception
java.lang.NullPointerException: null
	at josegamerpt.realscoreboard.scoreboard.animate.ScrollableString.<init>(ScrollableString.java:22) ~[?:?]
	at josegamerpt.realscoreboard.player.SBPlayer$1.run(SBPlayer.java:70) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-2040c4c-94cb030]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-2040c4c-94cb030]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-2040c4c-94cb030]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
`
@JoseGamerPT

**Comment by JoseGamerPT** [comment]
Hi there.
It seems like you are having problems with one of your scrollable strings.

**Comment by terencekam** [comment]
What is scrollable strings

**Comment by terencekam** [comment]
I just have three plugin Vault ,API But I make it based on bungee
@JoseGamerPT

**Comment by JoseGamerPT** [comment]
You have scrollable strings into the scoreboard config.
See the exemple config.yml on the repository.

**Comment by terencekam** [comment]
doesn't work,the config.yml set to default still not working

**Comment by JoseGamerPT** [comment]
Does it work when you try to isolate the plugin from others?

**Comment by terencekam** [comment]
it sounds crazy ,i redownload it and it works well

**Comment by JoseGamerPT** [comment]
that´s weird, but glad you got it working!
