### ISSUE TITLE
BUG Realscroeboard 1.16.1 

### ISSUE THREAD

**Issue by iLiDanMoon** [JoseGamerPT/RealScoreboard#21]
[18:40:08] [Server thread/WARN]: [RealScoreboard] Task #368135 for RealScoreboard v5-7-2020 Build 1 generated an exception
java.lang.NullPointerException: null
	at josegamerpt.realscoreboard.managers.PlayerManager$1.run(PlayerManager.java:65) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-74]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[18:40:08] [Server thread/WARN]: [RealScoreboard] Task #368136 for RealScoreboard v5-7-2020 Build 1 generated an exception
java.lang.NullPointerException: null
	at josegamerpt.realscoreboard.managers.PlayerManager$1.run(PlayerManager.java:65) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-74]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-74]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[18:40:08] [Server thread/WARN]: [RealScoreboard] Task #368137 for RealScoreboard v5-7-2020 Build 1 generated an exception
java.lang.NullPointerException: null

**Comment by JoseGamerPT** [comment]
Hi there. Please reload the server and check for PlayerData entry in your config.yml
