### ISSUE TITLE
much warnings in consol, its a spam from this plugin!

### ISSUE THREAD

**Issue by vinziiiz** [JoseGamerPT/RealScoreboard#5]
This are whats some comming upp all time long in my consol after i installed realscoreboard. I think any are problem with the code or anything there else? 

[WARNING] [RealScoreboard] Task #2725 for RealScoreboard v8-2-2020 Build 1 generated an exception

java.lang.NullPointerException: null

at josegamerpt.realscoreboard.player.SBPlayer$1.run(SBPlayer.java:75) ~[?:?]

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]

at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]

at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by JoseGamerPT** [comment]
Hi there! Thanks for contacting me.
Can you send more info about your server?

**Comment by vinziiiz** [comment]
The server are a spigot 1.15.2 server hosted on server.pro with towny & minigames. I dont know who info about the server you will have?

**Comment by JoseGamerPT** [comment]
Could the plugin be in conflict with other plugins?
